spring:
  datasource:
    url: jdbc:hsqldb:mem:accountdb
    username: SA
    password:
    driver-class-name: org.hsqldb.jdbcDriver
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
